//! Code supporting the `db *` sub commands.

pub mod compile;
pub mod conf;
pub mod genes;
pub mod mk_inhouse;
pub mod to_bin;

/// Data structures for (de-)serialization as generated by `prost-build`.
pub mod pbs {
    include!(concat!(env!("OUT_DIR"), "/varfish.v1.svs.rs"));
}
